name: "Composite Action"
description: "A simple composite action example"
inputs:
  example-input:
    description: "An example input"
    required: true
outputs:
  example-output:
    description: "An example output"
    value: ${{ steps.set-output.outputs.example-output }}
runs:
  using: "composite"
  steps:
    - name: Step 1 - Echo the input
      run: echo "Input is - ${{ inputs.example-input }}"
      shell: bash

    - name: Step 2 - Set the output
      id: set-output
      run: |
        echo "example-output=Hello from the composite action" >> $GITHUB_OUTPUT
      shell: bash

    - name: Debug Output
      run: cat $GITHUB_OUTPUT
      shell: bash
