name: 1 - Manual Workflow Example

on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "This is a manually triggered workflow!"
