name: 9 - Branch Based Workflow Execution - Master

on:
  push:
    branches:
      - master

jobs:
  master-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Master Branch
        run: echo "This workflow runs on the master branch."
