name: 10 - Using Data from Triggering Workflow - Second

on:
  workflow_run:
    workflows: ["10 - Using Data from Triggering Workflow - First"]
    types:
      - completed

permissions: read-all

jobs:
  use-message:
    runs-on: ubuntu-latest
    steps:
      - name: Debug output
        run: |
          echo "token = ${{ secrets.GH_WORKFLOW_TOKEN }}"
          echo "run-id = ${{ github.event.workflow_run.id }}"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: message
          github-token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          repository: olsido/github-workflow-dependencies-demo
          run-id: ${{ github.event.workflow_run.id }}
          path: ./
      - name: Read and echo the message
        run: |
          cat message.txt
