name: 10 - Using Data from Triggering Workflow - Second

on:
  workflow_run:
    workflows: ["10 - Using Data from Triggering Workflow - First"]
    types:
      - completed

jobs:
  use-message:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the message from the first workflow
        run: echo "Message from the first workflow - ${{ github.event.workflow_run.outputs.message }}"
