name: 10 - Using Data from Triggering Workflow - Second

on:
  workflow_run:
    workflows: ["10 - Using Data from Triggering Workflow - First"]
    types:
      - completed

jobs:
  use-message:
    runs-on: ubuntu-latest
    steps:
      - name: Download message artifact
        uses: actions/download-artifact@v4
        with:
          name: message

      - name: Read and echo message
        run: |
          cat message.txt
