name: 10 - Using Data from Triggering Workflow - Second

on:
  workflow_run:
    workflows: ["10 - Using Data from Triggering Workflow - First"]
    types:
      - completed

jobs:
  use-message:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: message
          github-token: ${{ secrets.GH_PAT }}
          path: ./
      - name: Unzip artifact
        run: unzip message.zip
      - name: Read and echo the message
        run: |
          cat message.txt
