name: 2 - Reusable Workflow Simple Example - Parent Workflow

on:
  workflow_dispatch:

jobs:
  before-child-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo before calling Child
        run: echo "This is the parent workflow, before calling the child workflow."

  child-workflow:
    needs: before-child-workflow
    uses: ./.github/workflows/2-reusable-workflow-simple-example--child-workflow.yml

  after-child-workflow:
    needs: child-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Echo after calling Child
        run: echo "This is the parent workflow, after the child workflow has completed."
