name: 2 - Reusable Workflow Simple Example - Child Workflow

on:
  workflow_call:

jobs:
  echo-from-child:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Child
        run: echo "This is the child workflow."
