name: 2 - Reusable Workflow Simple Example - Parent Workflow

on:
  workflow_dispatch:

jobs:
  call-child-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo before calling Child
        run: echo "This is the parent workflow, before calling the child workflow."
      - name: Call Child Workflow
        uses: ./.github/workflows/2-reusable-workflow-simple-example--child-workflow.yml
      - name: Echo after calling Child
        run: echo "This is the parent workflow, after the child workflow has completed."
