name: 3 - Reusable Workflow with Inputs and Secrets - Child Workflow

on:
  workflow_call:
    inputs:
      example-input:
        description: 'An example input'
        required: true
        type: string
    secrets:
      example-secret:
        description: 'An example secret'
        required: true

jobs:
  echo-from-child:
    runs-on: ubuntu-latest
    steps:
      - name: Echo from Child
        run: echo "This is the child workflow. Input - ${{ inputs.example-input }}."

      - name: Verify Secret
        run: |
          if [ "${{ secrets.example-secret }}" == "1234567" ]; then
            echo "The secret is correct."
          else
            echo "The secret is incorrect."
          fi
