name: 3 - Reusable Workflow with Inputs and Secrets - Parent Workflow

on:
  workflow_dispatch:
    inputs:
      example-input:
        description: 'An example input'
        required: true
        default: 'Hello, World!'

jobs:
  before-child-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Echo before calling Child
        run: echo "This is the parent workflow, before calling the child workflow."

  child-workflow:
    needs: before-child-workflow
    uses: ./.github/workflows/3-reusable-workflow-with-inputs-and-secrets--child-workflow.yml
    with:
      example-input: ${{ github.event.inputs.example-input }}
    secrets:
      example-secret: ${{ secrets.EXAMPLE_SECRET }}

  after-child-workflow:
    needs: child-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Echo after calling Child
        run: echo "This is the parent workflow, after the child workflow has completed."
