name: 4 - Using Outputs from Reusable Workflow - Child Workflow

on:
  workflow_call:

jobs:
  echo-from-child:
    runs-on: ubuntu-latest
    outputs:
      child-output: ${{ steps.generate-output.outputs.child-output }} # Reference the output from the step
    steps:
      - name: Generate Output
        id: generate-output # Step ID
        run: echo "child-output=Hello from the child workflow" >> $GITHUB_OUTPUT # Set the output

      - name: Echo from Child
        run: echo "This is the child workflow."
