name: 5 - Nesting Reusable Workflows - Caller Workflow

on:
  workflow_dispatch:

jobs:
  before-called-workflow-1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo before calling Called Workflow 1
        run: echo "This is the caller workflow, before calling Called Workflow 1."

  call-called-workflow-1:
    needs: before-called-workflow-1
    uses: ./.github/workflows/5-nesting-reusable-workflows--called-workflow-1.yml

  after-called-workflow-1:
    needs: call-called-workflow-1
    runs-on: ubuntu-latest
    steps:
      - name: Echo after calling Called Workflow 1
        run: echo "This is the caller workflow, after calling Called Workflow 1."
