name: 5 - Nesting Reusable Workflows - Called Workflow 2

on:
  workflow_call:

jobs:
  before-called-workflow-3:
    runs-on: ubuntu-latest
    steps:
      - name: Echo before calling Called Workflow 3
        run: echo "This is Called Workflow 2, before calling Called Workflow 3."

  call-called-workflow-3:
    needs: before-called-workflow-3
    uses: ./.github/workflows/5-nesting-reusable-workflows--called-workflow-3.yml

  after-called-workflow-3:
    needs: call-called-workflow-3
    runs-on: ubuntu-latest
    steps:
      - name: Echo after calling Called Workflow 3
        run: echo "This is Called Workflow 2, after calling Called Workflow 3."
