name: 6 - Composite Action Example

on:
  workflow_dispatch:

jobs:
  use-composite-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Echo before invoking Composite Action
        run: echo "About to invoke the composite action"

      - name: Run Composite Action
        id: composite-action
        uses: ./.github/actions/6-composite-action--definition
        with:
          example-input: "This is an example input"

      - name: Echo the output from the composite action
        run: echo "Output from composite action - ${{ steps.composite-action.outputs.example-output }}"
