name: 7 - Second Workflow

on:
  workflow_run:
    workflows: ["7 - First Workflow"]
    types:
      - completed

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is Second Workflow"
