name: 7 - Second Workflow

on:
  workflow_run:
    workflows: ["7 - First Workflow"]
    types:
      - completed

jobs:
  second-workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: Second Workflow Only Step
        run: echo "This is the second workflow"
