name: 8 - Sequential Workflows - Final

on:
  workflow_run:
    workflows: ["8 - Sequential Workflows - Success", "8 - Sequential Workflows - Failure"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Success Job Step
        run: echo "The previous workflow succeeded, so this job will run."

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Failure Job Step
        run: echo "The previous workflow failed, so this job will run."
